import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "BlenderLab — Generate 3D Assets from Python Scripts",
  description:
    "Upload a Python script and get back 3D model files (.glb, .fbx, .stl, .obj, .usd) generated by Blender running headlessly on GitHub Actions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <body>
        <div className="app-container">
          {/* Header */}
          <header className="app-header">
            <div className="header-inner">
              <Link href="/" className="logo">
                <div className="logo-icon">BL</div>
                <div className="logo-text">
                  BlenderLab<span>.dev</span>
                </div>
              </Link>
              <div className="header-links">
                <Link href="/guide" className="header-link">
                  📚 Guide
                </Link>
                <a
                  href="https://github.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="header-link"
                >
                  GitHub
                </a>
              </div>
            </div>
          </header>

          {/* Main */}
          <main className="main-content">{children}</main>

          {/* Footer */}
          <footer className="app-footer">
            <p className="footer-text">
              BlenderLab — Headless Blender on GitHub Actions
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
