import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "BlenderLab — Generate 3D Assets from Python Scripts",
  description:
    "Upload a Python script and get back 3D model files (.glb, .fbx, .stl, .obj, .usd) generated by Blender running headlessly on GitHub Actions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="app-container">
          {/* Header */}
          <header className="app-header">
            <div className="header-inner">
              <Link href="/" className="logo">
                <div className="logo-icon">BL</div>
                <div className="logo-text">
                  BlenderLab<span>.dev</span>
                </div>
              </Link>
              <div className="header-links">
                <a
                  href="https://github.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="header-link"
                >
                  GitHub
                </a>
              </div>
            </div>
          </header>

          {/* Main */}
          <main className="main-content">{children}</main>

          {/* Footer */}
          <footer className="app-footer">
            <p className="footer-text">
              BlenderLab — Headless Blender on GitHub Actions
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
